var main = document.getElementById("main");
if(window.location.href.split('=').pop() == 'join'){
main.innerHTML = "<h3>Document</h3><h1>Join The NSAA</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/joinTheNSAA.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/JoinTheNSAA.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/16szflc17pVzudVodhALenzLEz9nw56v54x7-fSfQWTU/edit?usp=sharing\">View Online (Google Docs)</a></li><li><a href=\"documents/JoinTheNSAA.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'marketvalues'){
main.innerHTML = "<h3>Document</h3><h1>Market Values</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/marketValues.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/Marketvalues.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/1469JW5RXMZbX6_EBjXkXOBkW4nMBPZVUWARfRAOPRKc/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/Marketvalues.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'protocols'){
main.innerHTML = "<h3>Document</h3><h1>Protocols</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/Protocols.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/Protocols.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/16ibdN9ncqo7k2T-R_XzqaWsIxLFcAETJyP04QzC6fQU/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/Protocols.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'edgenuity'){
main.innerHTML = "<h3>Document</h3><h1>Edgenuity Article</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/WhyEdgenuityIsNotWhereKidsShouldBeLearning.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/WhyEdgenuityisnotwherekidsshouldbelearning.zip\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/1Y39m6C2grpP3RduoBGirxf-oDr0dZBr3feVXqfcEbDE/edit?usp=sharing\">View Online (Google Docs)</a></li><li><a href=\"documents/WhyEdgenuityisnotwherekidsshouldbelearning.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'constitution'){
main.innerHTML = "<h3>Document</h3><h1>NSAA Constitution</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/NSAAConstitution.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/NSAAConstitution.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/1-8WVdaoJC47CHjJSdzVABSx_Cio94U2bMfvzNNXgApU/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/NSAAConstitution.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'dayreports'){
main.innerHTML = "<h3>Slideshow</h3><h1>NSAA Day Reports</h1><hr><h5>Due to this document's the frequency of updating, some links may not be up to date.</h5><h3>Downloads:</h3><ul><li><a href=\"documents/NSAADAYREPORTS.pptx\" download>PowerPoint Presentation (<i>.pptx</i>)</a></li><li><a href=\"documents/NSAA DAY REPORTS.pdf\" download>PDF Document (<i>.pdf</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/presentation/d/1I3BTWr-JhBe3Nxdt-R2JDRvcw_h1ZhRKY4hfBO_RG3k/edit#slide=id.g7d5af3231eb3e4b7_10\">View Online (Google Slides)</a></li><li><a href=\"documents/NSAA DAY REPORTS.pdf\">View Online (PDF)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'marketingstrategies'){
main.innerHTML = "<h3>Document</h3><h1>NSAA Marketing Strategies</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/NSAAMarketingStrategies.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/NSAAmarketingstrategies.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/1-vM9Wo8bgzdWTSWDBVSHk55WDPUa5CYHX8-h7VkpPAU/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/NSAAmarketingstrategies.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'membersandroles'){
main.innerHTML = "<h3>Slideshow</h3><h1>NSAA Members And Roles</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/NSAAMembersAndRoles.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/NSAAmembersandroles.pdf\" download>PDF Document (<i>.pdf</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/presentation/d/19ppgWIYkVegbjhj_muG06HPBuWkv_oeKHrfUALy_QjU\">View Online (Google Docs)</a></li><li><a href=\"documents/NSAAmembersandroles.pdf\">View Online (PDF)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'policies'){
main.innerHTML = "<h3>Document</h3><h1>NSAA Policies</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/policiesOfTheNSAA.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/PoliciesoftheNSAA.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/1Rh4imNaCAWMyupfhtbFMtYi-gyA-b2QqNT0oDdixcSg/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/PoliciesoftheNSAA.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'specialcollections'){
main.innerHTML = "<h3>Document</h3><h1>Special Collections</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/specialCollections.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/Specialcollections.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/12JxMLpud-l9uvRtDtD4x2vbLnFfUBRx2s9p6E819dyY/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/Specialcollections.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'projectandoperationarchives'){
main.innerHTML = "<h3>Document</h3><h1>Project And Operation Archives</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/NSAAProjectAndOperationArchives.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/NSAAProjectAndOperationArchives.zip\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/10dkZ7Sx73mPMKjiL1QtHo-FP9INFFg4b8r6As915EWE/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/NSAAProjectandOperationArchives.html\">View Online (HTML)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'nsaahistory'){
main.innerHTML = '<h3>Video</h3><h1>NSAA History</h1><hr><iframe width="853" height="480" src="https://www.youtube.com/embed/_wekFePg1Hk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';}
else if(window.location.href.split('=').pop() == 'scavengerlog'){
main.innerHTML = "<h3>Slideshow</h3><h1>Scavengers Log</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/NSAAScavengerLog.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/NSAAScavengerlog.pdf\" download>PDF Document (<i>.pdf</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/presentation/d/11ixTwPLNbrplpCl4thuiN9ebSdz3tLUumTXNDb5ECAM/edit#slide=id.p\">View Online (Google Docs)</a></li><li><a href=\"documents/NSAAScavengerlog.pdf\">View Online (PDF)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'terms'){
main.innerHTML = "<h3>Page</h3><h1>Terms</h1><hr><h4><i>This site (NSAA Backup Library) is provided as a public service and is intended for use by NSAA MEMBERS AND MEMBERS OF PARTNERING COMPANIES ONLY. At no time is it acceptable to redistribute, copy, or share any of the files or links on this site - Doing so will result in the violating member being fired from the NSAA. These rules are strict. If you are not a member of the NSAA, you must LEAVE THIS SITE IMMEDIATELY.</i></h4>";}
