var main = document.getElementById("main");
if(window.location.href.split('=').pop() == 'join'){
main.innerHTML = "<h3>Document</h3><h1>Join The NSAA</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/joinTheNSAA.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/JoinTheNSAA.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/16szflc17pVzudVodhALenzLEz9nw56v54x7-fSfQWTU/edit?usp=sharing\">View Online (Google Docs)</a></li><li><a href=\"documents/JoinTheNSAA.html\">View Online (This Site)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'marketvalues'){
main.innerHTML = "<h3>Document</h3><h1>Market Values</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/marketValues.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/Marketvalues.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/1469JW5RXMZbX6_EBjXkXOBkW4nMBPZVUWARfRAOPRKc/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/Marketvalues.html\">View Online (This Site)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'protocols'){
main.innerHTML = "<h3>Document</h3><h1>Protocols</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/Protocols.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/Protocols.html\" download>HTML Webpage (<i>.html</i>)</a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/16ibdN9ncqo7k2T-R_XzqaWsIxLFcAETJyP04QzC6fQU/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/Protocols.html\">View Online (This Site)</a></li></ul>";}
else if(window.location.href.split('=').pop() == 'edgenuity'){
main.innerHTML = "<h3>Document</h3><h1>Edgenuity Article</h1><hr><h3>Downloads:</h3><ul><li><a href=\"documents/WhyEdgenuityIsNotWhereKidsShouldBeLearning.docx\" download>Word Document (<i>.docx</i>)</a></li><li><a href=\"documents/WhyEdgenuityisnotwherekidsshouldbelearning.html\" onclick=\"document.getElementById('files').click()\" download>HTML Webpage (<i>.html</i>)</a><a style=\"display:none;\" id=\"files\" href=\"documents/WhyEdgenuityisnotwherekidsshouldbelearning_files/\" download></a></li></ul><h3>Links:</h3><ul><li><a href=\"https://docs.google.com/document/d/16ibdN9ncqo7k2T-R_XzqaWsIxLFcAETJyP04QzC6fQU/edit\">View Online (Google Docs)</a></li><li><a href=\"documents/Protocols.html\">View Online (This Site)</a></li></ul>";}
		